### ISSUE TITLE
[enhancement] Shotcaller only information

### ISSUE THREAD

**Issue by kingeraser** [Targma/command-center#1]
I would like you to sperate the "statistic" and "full state" tabs from a normal member and the shotcaller/decision makers.

The shotcaller can login with a hash and is able to see the stats for the whole raid.
If anyone else connects to the server and has the wrong or no hash he wont be able to see any stats but his own(State).
This could be attached to the excisting "role" feature. The shotcalling role would need a field for hash.

**Comment by Targma** [comment]
I added some form of login for more details read section (link)[https://github.com/Targma/command-center#server]
